### ISSUE TITLE
Remove Notebook API support

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3176]
The Notebook API support was partially implemented but based on early Visual Studio Code APIs which have yet to be finalized. Since our support is experimental, it probably ought to have been in a feature branch. So we're planning to:

- [x] Turn off the GitHub actions which open new PRs updating our use of the experimental APIs
- [x] Remove the Notebook code from the extension itself
- [ ] Save the prototype in a feature branch to be revisited in the future

/cc @TylerLeonhardt @rjmholt @SydneyhSmith

**Comment by rjmholt** [comment]
Yeah I think the key issue for us is that we had assumed the VSCode notebook APIs would stabilise sooner than it has, so it was acceptable to take the incremental changes in the meantime.

We've proven the concept, but managing the update PRs has become an ongoing burden &mdash; the simplest solution is for us to wait for the API to be exposed stably by VSCode and then to re-enable our notebook integration code.

**Comment by andschwa** [comment]
That "feature branch" is just the fact that it's in the history as a merged PR 😅

**Comment by dkattan** [comment]
Damn, I was just sitting down to finally play with this lol.

**Comment by andschwa** [comment]
It'll come back one day! Just when the VS Code API is stable and we can integrate with it properly. For now, we're focussing on much-needed stabilization work for the extension. 😄
