### ISSUE TITLE
Remaining work for 1.0

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#513]
## Needed for 1.0

- [ ] Language features for classes - Kapil 
  - [ ] Go to definition, find references, rename symbol https://github.com/PowerShell/PowerShellEditorServices/issues/14
  - [ ] Document and workspace symbol providers https://github.com/PowerShell/vscode-powershell/issues/3
- [ ] Module-wide symbol indexing and operations - Kapil
   - https://github.com/PowerShell/PowerShellEditorServices/issues/394
   - https://github.com/PowerShell/PowerShellEditorServices/issues/395
   - https://github.com/PowerShell/vscode-powershell/issues/586
- [x] Save remote file from psedit - David https://github.com/PowerShell/vscode-powershell/issues/583
- [ ] User Guide, especially ISE-compatible configuration instructions - David + contributors https://github.com/PowerShell/vscode-powershell/issues/584
- [ ] Complete $psEditor extensibility API + David
  - [ ] Saving file buffer https://github.com/PowerShell/PowerShellEditorServices/issues/258
  - Markers https://github.com/PowerShell/PowerShellEditorServices/issues/235
- [ ] Polish New File/Project experience - David https://github.com/PowerShell/vscode-powershell/issues/587
- [ ] Increase test coverage - high level scenario validation - David 
- [ ] Fix P1 bugs - David, Kapil
- [ ] Localization infrastructure in place (all strings should be coming from resource files) - David
  - [ ] Localization of PowerShell extension https://github.com/PowerShell/vscode-powershell/issues/585
  - [ ] Localization of PowerShell Editor Services 

Targeting 1.0.0-beta1 early May.
